// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/auth/auth.proto

package go_micro_srv_tenno_ucenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type LoginRequest struct {
	Phone                uint64   `protobuf:"varint,1,opt,name=phone,proto3" json:"phone,omitempty"`
	Appid                uint32   `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetPhone() uint64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *LoginRequest) GetAppid() uint32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *LoginRequest) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type SDKLoginRequest struct {
	Unionid              string   `protobuf:"bytes,1,opt,name=unionid,proto3" json:"unionid,omitempty"`
	Appid                uint32   `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Type                 uint32   `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	NickName             string   `protobuf:"bytes,4,opt,name=nickName,proto3" json:"nickName,omitempty"`
	Gender               int32    `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Avatar               string   `protobuf:"bytes,6,opt,name=avatar,proto3" json:"avatar,omitempty"`
	City                 string   `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	Province             string   `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	Country              string   `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SDKLoginRequest) Reset()         { *m = SDKLoginRequest{} }
func (m *SDKLoginRequest) String() string { return proto.CompactTextString(m) }
func (*SDKLoginRequest) ProtoMessage()    {}
func (*SDKLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{1}
}

func (m *SDKLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SDKLoginRequest.Unmarshal(m, b)
}
func (m *SDKLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SDKLoginRequest.Marshal(b, m, deterministic)
}
func (m *SDKLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SDKLoginRequest.Merge(m, src)
}
func (m *SDKLoginRequest) XXX_Size() int {
	return xxx_messageInfo_SDKLoginRequest.Size(m)
}
func (m *SDKLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SDKLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SDKLoginRequest proto.InternalMessageInfo

func (m *SDKLoginRequest) GetUnionid() string {
	if m != nil {
		return m.Unionid
	}
	return ""
}

func (m *SDKLoginRequest) GetAppid() uint32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *SDKLoginRequest) GetType() uint32 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *SDKLoginRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *SDKLoginRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *SDKLoginRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *SDKLoginRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SDKLoginRequest) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *SDKLoginRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

type CheckRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Appid                uint32   `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{2}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *CheckRequest) GetAppid() uint32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *CheckRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type LogoutRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Appid                uint32   `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Token                string   `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogoutRequest) Reset()         { *m = LogoutRequest{} }
func (m *LogoutRequest) String() string { return proto.CompactTextString(m) }
func (*LogoutRequest) ProtoMessage()    {}
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{3}
}

func (m *LogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogoutRequest.Unmarshal(m, b)
}
func (m *LogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogoutRequest.Marshal(b, m, deterministic)
}
func (m *LogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogoutRequest.Merge(m, src)
}
func (m *LogoutRequest) XXX_Size() int {
	return xxx_messageInfo_LogoutRequest.Size(m)
}
func (m *LogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LogoutRequest proto.InternalMessageInfo

func (m *LogoutRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *LogoutRequest) GetAppid() uint32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *LogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type SmsRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Appid                int32    `protobuf:"varint,2,opt,name=appid,proto3" json:"appid,omitempty"`
	Phone                uint64   `protobuf:"varint,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SmsRequest) Reset()         { *m = SmsRequest{} }
func (m *SmsRequest) String() string { return proto.CompactTextString(m) }
func (*SmsRequest) ProtoMessage()    {}
func (*SmsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{4}
}

func (m *SmsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SmsRequest.Unmarshal(m, b)
}
func (m *SmsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SmsRequest.Marshal(b, m, deterministic)
}
func (m *SmsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SmsRequest.Merge(m, src)
}
func (m *SmsRequest) XXX_Size() int {
	return xxx_messageInfo_SmsRequest.Size(m)
}
func (m *SmsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SmsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SmsRequest proto.InternalMessageInfo

func (m *SmsRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SmsRequest) GetAppid() int32 {
	if m != nil {
		return m.Appid
	}
	return 0
}

func (m *SmsRequest) GetPhone() uint64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_82b5829f48cfb8e5, []int{5}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.tenno.ucenter.LoginRequest")
	proto.RegisterType((*SDKLoginRequest)(nil), "go.micro.srv.tenno.ucenter.SDKLoginRequest")
	proto.RegisterType((*CheckRequest)(nil), "go.micro.srv.tenno.ucenter.CheckRequest")
	proto.RegisterType((*LogoutRequest)(nil), "go.micro.srv.tenno.ucenter.LogoutRequest")
	proto.RegisterType((*SmsRequest)(nil), "go.micro.srv.tenno.ucenter.SmsRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.tenno.ucenter.Response")
}

func init() { proto.RegisterFile("proto/auth/auth.proto", fileDescriptor_82b5829f48cfb8e5) }

var fileDescriptor_82b5829f48cfb8e5 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xc1, 0xaa, 0xd4, 0x30,
	0x14, 0x86, 0xad, 0xd3, 0x76, 0x3a, 0x87, 0x3b, 0x28, 0xe1, 0x2a, 0x61, 0x70, 0x31, 0x14, 0x91,
	0x8a, 0x50, 0x41, 0x9f, 0x40, 0x74, 0xa5, 0x73, 0xef, 0x22, 0x5d, 0x5d, 0x5c, 0x48, 0x6d, 0x0f,
	0x6d, 0x18, 0x9a, 0xd4, 0x34, 0x19, 0x98, 0x07, 0xf5, 0x29, 0x7c, 0x09, 0x69, 0xd2, 0x5e, 0xab,
	0x30, 0xb5, 0x82, 0x9b, 0xe1, 0xfc, 0x87, 0xc9, 0x97, 0x73, 0xf2, 0xff, 0x14, 0x9e, 0xb4, 0x4a,
	0x6a, 0xf9, 0x3a, 0x37, 0xba, 0xb6, 0x3f, 0xa9, 0xd5, 0x64, 0x57, 0xc9, 0xb4, 0xe1, 0x85, 0x92,
	0x69, 0xa7, 0x4e, 0xa9, 0x46, 0x21, 0x64, 0x6a, 0x0a, 0x14, 0x1a, 0x55, 0x7c, 0x0b, 0x57, 0x07,
	0x59, 0x71, 0xc1, 0xf0, 0x9b, 0xc1, 0x4e, 0x93, 0x6b, 0x08, 0xda, 0x5a, 0x0a, 0xa4, 0xde, 0xde,
	0x4b, 0x7c, 0xe6, 0x44, 0xdf, 0xcd, 0xdb, 0x96, 0x97, 0xf4, 0xe1, 0xde, 0x4b, 0xb6, 0xcc, 0x09,
	0x42, 0xc0, 0x2f, 0x64, 0x89, 0x74, 0xb5, 0xf7, 0x92, 0x80, 0xd9, 0x3a, 0xfe, 0xe1, 0xc1, 0xa3,
	0xec, 0xc3, 0xa7, 0xdf, 0x98, 0x14, 0xd6, 0x46, 0x70, 0x29, 0x78, 0x69, 0xa9, 0x1b, 0x36, 0xca,
	0xcb, 0x5c, 0x7d, 0x6e, 0x1d, 0x77, 0xcb, 0x6c, 0x4d, 0x76, 0x10, 0x09, 0x5e, 0x1c, 0x6f, 0xf3,
	0x06, 0xa9, 0x6f, 0x21, 0xf7, 0x9a, 0x3c, 0x85, 0xb0, 0x42, 0x51, 0xa2, 0xa2, 0x81, 0x9d, 0x64,
	0x50, 0x7d, 0x3f, 0x3f, 0xe5, 0x3a, 0x57, 0x34, 0xb4, 0x27, 0x06, 0x65, 0xe7, 0xe6, 0xfa, 0x4c,
	0xd7, 0xb6, 0x6b, 0xeb, 0x9e, 0xdf, 0x2a, 0x79, 0xe2, 0xa2, 0x40, 0x1a, 0x39, 0xfe, 0xa8, 0xfb,
	0xf9, 0x0b, 0x69, 0x84, 0x56, 0x67, 0xba, 0x71, 0xf3, 0x0f, 0x32, 0x3e, 0xc0, 0xd5, 0xfb, 0x1a,
	0x8b, 0xe3, 0xb8, 0xe9, 0x63, 0x58, 0x99, 0x61, 0x4b, 0x9f, 0xf5, 0xe5, 0x85, 0x0d, 0xaf, 0x21,
	0xd0, 0xf2, 0x88, 0xc2, 0xae, 0xb8, 0x61, 0x4e, 0xc4, 0x37, 0xb0, 0x3d, 0xc8, 0x4a, 0x1a, 0xfd,
	0x7f, 0x70, 0x1f, 0x01, 0xb2, 0xa6, 0x5b, 0xc8, 0x0a, 0x26, 0x2c, 0x17, 0x80, 0xd5, 0x24, 0x00,
	0xf1, 0x33, 0x88, 0x18, 0x76, 0xad, 0x14, 0x1d, 0xf6, 0xa4, 0xa6, 0xab, 0x06, 0x2b, 0xfb, 0xf2,
	0xcd, 0xf7, 0x15, 0xf8, 0xef, 0x8c, 0xae, 0xc9, 0x1d, 0x04, 0xd6, 0x79, 0x92, 0xa4, 0x97, 0x33,
	0x97, 0x4e, 0xc3, 0xb1, 0x7b, 0x3e, 0xf7, 0xcf, 0xf1, 0xce, 0xf8, 0x01, 0xf9, 0x02, 0xd1, 0x98,
	0x2b, 0xf2, 0x6a, 0xee, 0xcc, 0x1f, 0xe9, 0x5b, 0x7c, 0xc1, 0x1d, 0x04, 0xd6, 0xcb, 0xf9, 0xd9,
	0xa7, 0x76, 0x2f, 0x46, 0x7f, 0x86, 0xd0, 0x19, 0x4b, 0x5e, 0xfe, 0xe5, 0x5d, 0x7e, 0x99, 0xff,
	0x0f, 0x73, 0xaf, 0x33, 0x14, 0x65, 0x76, 0x93, 0x91, 0x17, 0xb3, 0xef, 0x72, 0x9f, 0x85, 0xa5,
	0xe8, 0xaf, 0xa1, 0xfd, 0x7e, 0xbc, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0xea, 0xf9, 0x8d, 0x5f,
	0x58, 0x04, 0x00, 0x00,
}
