// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/bind/bind.proto

package go_micro_srv_tenno_ucenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type BindRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AccountType          uint32   `protobuf:"varint,2,opt,name=accountType,proto3" json:"accountType,omitempty"`
	Account              string   `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BindRequest) Reset()         { *m = BindRequest{} }
func (m *BindRequest) String() string { return proto.CompactTextString(m) }
func (*BindRequest) ProtoMessage()    {}
func (*BindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1153fc68fcdcaec, []int{0}
}

func (m *BindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BindRequest.Unmarshal(m, b)
}
func (m *BindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BindRequest.Marshal(b, m, deterministic)
}
func (m *BindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BindRequest.Merge(m, src)
}
func (m *BindRequest) XXX_Size() int {
	return xxx_messageInfo_BindRequest.Size(m)
}
func (m *BindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BindRequest proto.InternalMessageInfo

func (m *BindRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *BindRequest) GetAccountType() uint32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *BindRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type UnbindRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AccountType          uint32   `protobuf:"varint,2,opt,name=accountType,proto3" json:"accountType,omitempty"`
	SmsCode              uint32   `protobuf:"varint,3,opt,name=smsCode,proto3" json:"smsCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnbindRequest) Reset()         { *m = UnbindRequest{} }
func (m *UnbindRequest) String() string { return proto.CompactTextString(m) }
func (*UnbindRequest) ProtoMessage()    {}
func (*UnbindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1153fc68fcdcaec, []int{1}
}

func (m *UnbindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnbindRequest.Unmarshal(m, b)
}
func (m *UnbindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnbindRequest.Marshal(b, m, deterministic)
}
func (m *UnbindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnbindRequest.Merge(m, src)
}
func (m *UnbindRequest) XXX_Size() int {
	return xxx_messageInfo_UnbindRequest.Size(m)
}
func (m *UnbindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnbindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnbindRequest proto.InternalMessageInfo

func (m *UnbindRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *UnbindRequest) GetAccountType() uint32 {
	if m != nil {
		return m.AccountType
	}
	return 0
}

func (m *UnbindRequest) GetSmsCode() uint32 {
	if m != nil {
		return m.SmsCode
	}
	return 0
}

type GetBindListRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBindListRequest) Reset()         { *m = GetBindListRequest{} }
func (m *GetBindListRequest) String() string { return proto.CompactTextString(m) }
func (*GetBindListRequest) ProtoMessage()    {}
func (*GetBindListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1153fc68fcdcaec, []int{2}
}

func (m *GetBindListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBindListRequest.Unmarshal(m, b)
}
func (m *GetBindListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBindListRequest.Marshal(b, m, deterministic)
}
func (m *GetBindListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBindListRequest.Merge(m, src)
}
func (m *GetBindListRequest) XXX_Size() int {
	return xxx_messageInfo_GetBindListRequest.Size(m)
}
func (m *GetBindListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBindListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBindListRequest proto.InternalMessageInfo

func (m *GetBindListRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1153fc68fcdcaec, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*BindRequest)(nil), "go.micro.srv.tenno.ucenter.BindRequest")
	proto.RegisterType((*UnbindRequest)(nil), "go.micro.srv.tenno.ucenter.UnbindRequest")
	proto.RegisterType((*GetBindListRequest)(nil), "go.micro.srv.tenno.ucenter.GetBindListRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.tenno.ucenter.Response")
}

func init() { proto.RegisterFile("proto/bind/bind.proto", fileDescriptor_b1153fc68fcdcaec) }

var fileDescriptor_b1153fc68fcdcaec = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x92, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xed, 0xee, 0xb2, 0xba, 0x53, 0x0a, 0x12, 0x10, 0xca, 0xe2, 0xa1, 0x04, 0xd1, 0x7a,
	0x89, 0xa0, 0x6f, 0xa0, 0x07, 0x2f, 0x9e, 0x82, 0x8b, 0x87, 0xc5, 0x83, 0x6d, 0x87, 0x25, 0x87,
	0x4e, 0x6a, 0x27, 0x15, 0x7c, 0x1e, 0x5f, 0x54, 0x12, 0xb6, 0x50, 0x91, 0x2d, 0x85, 0xbd, 0x24,
	0xf3, 0x67, 0x32, 0xff, 0x1f, 0x3e, 0x02, 0x17, 0x4d, 0x6b, 0x9d, 0xbd, 0x2b, 0x0c, 0x55, 0x61,
	0x51, 0x41, 0x8b, 0xf5, 0xce, 0xaa, 0xda, 0x94, 0xad, 0x55, 0xdc, 0x7e, 0x29, 0x87, 0x44, 0x56,
	0x75, 0x25, 0x92, 0xc3, 0x56, 0x6e, 0x21, 0x7e, 0x34, 0x54, 0x69, 0xfc, 0xec, 0x90, 0x9d, 0x38,
	0x87, 0x79, 0x67, 0xaa, 0x34, 0xca, 0xa2, 0x7c, 0xa1, 0x7d, 0x29, 0x32, 0x88, 0x3f, 0xca, 0xd2,
	0x76, 0xe4, 0x5e, 0xbf, 0x1b, 0x4c, 0x67, 0x59, 0x94, 0x27, 0x7a, 0x78, 0x24, 0x52, 0x38, 0xdd,
	0xcb, 0x74, 0x9e, 0x45, 0xf9, 0x4a, 0xf7, 0x52, 0xbe, 0x43, 0xb2, 0xa1, 0xe2, 0x78, 0x7b, 0xae,
	0xf9, 0xc9, 0x56, 0x18, 0xec, 0x13, 0xdd, 0x4b, 0x79, 0x0d, 0xe2, 0x19, 0x9d, 0x7f, 0xfe, 0x8b,
	0x61, 0x77, 0x30, 0x43, 0x5e, 0xc2, 0x99, 0x46, 0x6e, 0x2c, 0x31, 0xfa, 0x6e, 0xcd, 0xbb, 0xd0,
	0x5d, 0x69, 0x5f, 0xde, 0xff, 0xcc, 0x60, 0xe1, 0x3d, 0xc4, 0xdb, 0x7e, 0xbf, 0x51, 0x87, 0x79,
	0xa9, 0x01, 0xac, 0xf5, 0xd5, 0xd8, 0xc5, 0x3e, 0x51, 0x9e, 0x88, 0x2d, 0x2c, 0x37, 0x14, 0xac,
	0x6f, 0xc7, 0x26, 0xfe, 0xa0, 0x9a, 0x6c, 0x8e, 0x10, 0x0f, 0x20, 0x08, 0x35, 0x36, 0xf6, 0x9f,
	0xd6, 0xd4, 0x98, 0x62, 0x19, 0xbe, 0xd2, 0xc3, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6f, 0x29,
	0x47, 0xe5, 0x63, 0x02, 0x00, 0x00,
}
