// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/base/base.proto

package go_micro_srv_tenno_ucenter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	// repeated uint64 uid = 1;
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56de8d0620b9cff, []int{0}
}

func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (m *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(m, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

type SetRequest struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	NickName             string   `protobuf:"bytes,2,opt,name=nickName,proto3" json:"nickName,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=userName,proto3" json:"userName,omitempty"`
	RealName             string   `protobuf:"bytes,4,opt,name=realName,proto3" json:"realName,omitempty"`
	Gender               int32    `protobuf:"varint,5,opt,name=gender,proto3" json:"gender,omitempty"`
	Age                  int32    `protobuf:"varint,6,opt,name=age,proto3" json:"age,omitempty"`
	Phone                uint64   `protobuf:"varint,7,opt,name=phone,proto3" json:"phone,omitempty"`
	Email                string   `protobuf:"bytes,8,opt,name=email,proto3" json:"email,omitempty"`
	Country              string   `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	Province             string   `protobuf:"bytes,10,opt,name=province,proto3" json:"province,omitempty"`
	City                 string   `protobuf:"bytes,11,opt,name=city,proto3" json:"city,omitempty"`
	Language             string   `protobuf:"bytes,12,opt,name=language,proto3" json:"language,omitempty"`
	Avatar               string   `protobuf:"bytes,13,opt,name=avatar,proto3" json:"avatar,omitempty"`
	State                int32    `protobuf:"varint,14,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetRequest) Reset()         { *m = SetRequest{} }
func (m *SetRequest) String() string { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()    {}
func (*SetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56de8d0620b9cff, []int{1}
}

func (m *SetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetRequest.Unmarshal(m, b)
}
func (m *SetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetRequest.Marshal(b, m, deterministic)
}
func (m *SetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetRequest.Merge(m, src)
}
func (m *SetRequest) XXX_Size() int {
	return xxx_messageInfo_SetRequest.Size(m)
}
func (m *SetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetRequest proto.InternalMessageInfo

func (m *SetRequest) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *SetRequest) GetNickName() string {
	if m != nil {
		return m.NickName
	}
	return ""
}

func (m *SetRequest) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *SetRequest) GetRealName() string {
	if m != nil {
		return m.RealName
	}
	return ""
}

func (m *SetRequest) GetGender() int32 {
	if m != nil {
		return m.Gender
	}
	return 0
}

func (m *SetRequest) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *SetRequest) GetPhone() uint64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *SetRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *SetRequest) GetCountry() string {
	if m != nil {
		return m.Country
	}
	return ""
}

func (m *SetRequest) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *SetRequest) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *SetRequest) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *SetRequest) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *SetRequest) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

type Response struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_e56de8d0620b9cff, []int{2}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "go.micro.srv.tenno.ucenter.GetRequest")
	proto.RegisterType((*SetRequest)(nil), "go.micro.srv.tenno.ucenter.SetRequest")
	proto.RegisterType((*Response)(nil), "go.micro.srv.tenno.ucenter.Response")
}

func init() { proto.RegisterFile("proto/base/base.proto", fileDescriptor_e56de8d0620b9cff) }

var fileDescriptor_e56de8d0620b9cff = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0x4d, 0x9b, 0xfe, 0x9b, 0xaa, 0xc8, 0xa2, 0xb2, 0x14, 0x91, 0x12, 0x44, 0x7a, 0x8a,
	0xa0, 0x6f, 0xe0, 0xa5, 0x78, 0xf1, 0x90, 0xe2, 0xd1, 0xc3, 0x36, 0x1d, 0x63, 0xb0, 0xd9, 0x8d,
	0xbb, 0x9b, 0x42, 0xdf, 0xcf, 0xc7, 0xf0, 0x61, 0x64, 0x66, 0x1b, 0x3d, 0x59, 0xf4, 0x12, 0xe6,
	0x37, 0xdf, 0xc7, 0xb7, 0x5f, 0xb2, 0x81, 0xb3, 0xda, 0x1a, 0x6f, 0x6e, 0x96, 0xca, 0x21, 0x3f,
	0x52, 0x66, 0x31, 0x29, 0x4c, 0x5a, 0x95, 0xb9, 0x35, 0xa9, 0xb3, 0x9b, 0xd4, 0xa3, 0xd6, 0x26,
	0x6d, 0x72, 0xd4, 0x1e, 0x6d, 0x72, 0x09, 0x30, 0x47, 0x9f, 0xe1, 0x7b, 0x83, 0xce, 0x8b, 0x13,
	0xe8, 0x36, 0xe5, 0x4a, 0x46, 0xd3, 0x68, 0x16, 0x67, 0x34, 0x26, 0x9f, 0x1d, 0x80, 0xc5, 0x1e,
	0x83, 0x98, 0xc0, 0x50, 0x97, 0xf9, 0xdb, 0xa3, 0xaa, 0x50, 0x76, 0xa6, 0xd1, 0x6c, 0x94, 0x7d,
	0x33, 0x69, 0x8d, 0x43, 0xcb, 0x5a, 0x37, 0x68, 0x2d, 0x93, 0x66, 0x51, 0xad, 0x59, 0x8b, 0x83,
	0xd6, 0xb2, 0x38, 0x87, 0x7e, 0x81, 0x7a, 0x85, 0x56, 0xf6, 0xa6, 0xd1, 0xac, 0x97, 0xed, 0x88,
	0x4e, 0x57, 0x05, 0xca, 0x3e, 0x2f, 0x69, 0x14, 0xa7, 0xd0, 0xab, 0x5f, 0x8d, 0x46, 0x39, 0xe0,
	0x46, 0x01, 0x68, 0x8b, 0x95, 0x2a, 0xd7, 0x72, 0xc8, 0xc1, 0x01, 0x84, 0x84, 0x41, 0x6e, 0x1a,
	0xed, 0xed, 0x56, 0x8e, 0x78, 0xdf, 0x22, 0x75, 0xa9, 0xad, 0xd9, 0x94, 0x3a, 0x47, 0x09, 0xa1,
	0x4b, 0xcb, 0x42, 0x40, 0x9c, 0x97, 0x7e, 0x2b, 0xc7, 0xbc, 0xe7, 0x99, 0xfc, 0x6b, 0xa5, 0x8b,
	0x86, 0xca, 0x1c, 0x06, 0x7f, 0xcb, 0xd4, 0x5d, 0x6d, 0x94, 0x57, 0x56, 0x1e, 0xb1, 0xb2, 0x23,
	0xea, 0xe4, 0xbc, 0xf2, 0x28, 0x8f, 0xb9, 0x7d, 0x80, 0xe4, 0x02, 0x86, 0x19, 0xba, 0xda, 0x68,
	0x87, 0xf4, 0x76, 0x95, 0x2b, 0xf8, 0xdb, 0x8e, 0x32, 0x1a, 0x6f, 0x3f, 0x22, 0x88, 0xef, 0x95,
	0x43, 0xf1, 0x0c, 0xe3, 0x39, 0xfa, 0x27, 0x87, 0xf6, 0x41, 0xbf, 0x18, 0x71, 0x9d, 0xfe, 0x7e,
	0xa3, 0xe9, 0xcf, 0x75, 0x4e, 0xae, 0xf6, 0xf9, 0xda, 0x73, 0x93, 0x03, 0x8a, 0x5f, 0xfc, 0x35,
	0x7e, 0xf1, 0xef, 0xf8, 0x65, 0x9f, 0x7f, 0xc3, 0xbb, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf9,
	0x47, 0x9a, 0x51, 0x9f, 0x02, 0x00, 0x00,
}
