// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/device/device.proto

/*
Package go_micro_srv_tenno_ucenter is a generated protocol buffer package.

It is generated from these files:
	proto/device/device.proto

It has these top-level messages:
	UpdateRequest
	GetRequest
	Response
*/
package go_micro_srv_tenno_ucenter

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Device service

type DeviceService interface {
	UpdateDevice(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*Response, error)
	GetDevice(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error)
}

type deviceService struct {
	c    client.Client
	name string
}

func NewDeviceService(name string, c client.Client) DeviceService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "go.micro.srv.tenno.ucenter"
	}
	return &deviceService{
		c:    c,
		name: name,
	}
}

func (c *deviceService) UpdateDevice(ctx context.Context, in *UpdateRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Device.UpdateDevice", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceService) GetDevice(ctx context.Context, in *GetRequest, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Device.GetDevice", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Device service

type DeviceHandler interface {
	UpdateDevice(context.Context, *UpdateRequest, *Response) error
	GetDevice(context.Context, *GetRequest, *Response) error
}

func RegisterDeviceHandler(s server.Server, hdlr DeviceHandler, opts ...server.HandlerOption) error {
	type device interface {
		UpdateDevice(ctx context.Context, in *UpdateRequest, out *Response) error
		GetDevice(ctx context.Context, in *GetRequest, out *Response) error
	}
	type Device struct {
		device
	}
	h := &deviceHandler{hdlr}
	return s.Handle(s.NewHandler(&Device{h}, opts...))
}

type deviceHandler struct {
	DeviceHandler
}

func (h *deviceHandler) UpdateDevice(ctx context.Context, in *UpdateRequest, out *Response) error {
	return h.DeviceHandler.UpdateDevice(ctx, in, out)
}

func (h *deviceHandler) GetDevice(ctx context.Context, in *GetRequest, out *Response) error {
	return h.DeviceHandler.GetDevice(ctx, in, out)
}
